### ISSUE TITLE
babel-plugin-react-intl

### ISSUE THREAD

**Issue by BANG88** [frostney/react-intl-native#1]
Can we work with https://github.com/yahoo/babel-plugin-react-intl?

**Comment by frostney** [comment]
As far as I know it should work fine as it's just as a small wrapper around `react-intl` and uses the same properties as the components exposed by `react-intl`. That being said, I currently don't have a project where I'm using `babel-plugin-react-intl`, so it would take me a bit of time to set one up.
Please let me know if doesn't work and feel free to submit a pull request in that case.

**Comment by BaptisteT** [comment]
No, actually this is not working. The script does not extract react-intl-native strings.
